version: 2
jobs:
  build:
    working_directory: ~/c2
    docker:
      - image: circleci/python:3.6-browsers
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:10.3-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:

      # Checkout and set permissions
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages

      # Restore cache
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "web/Pipfile.lock" }}

      # Install
      - run:
          command: |
            cd ./web
            pipenv install

      # Save cache
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "web/Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"

      # Actual tests!
      - run:
          command: |
            cd ./web
            pipenv run "invoke test"

      # Store results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
