# Generated by Django 2.0.3 on 2018-04-09 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20180409_1319'),
        ('account', '0006_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ethnicity',
                'verbose_name_plural': 'Ethnicities',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Race',
                'verbose_name_plural': 'Races',
            },
        ),
        migrations.CreateModel(
            name='UserRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_ethnicities', models.CharField(max_length=255)),
                ('ethnicities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Ethnicity')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Race')),
            ],
            options={
                'verbose_name': 'UserRace',
                'verbose_name_plural': 'UserRaces',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='locations',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('type', 'H'), ('type', 'W'), _connector='OR'), to='location.Location'),
        ),
        migrations.AddField(
            model_name='userrace',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ethnicity',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Race'),
        ),
        migrations.AddField(
            model_name='user',
            name='races',
            field=models.ManyToManyField(blank=True, through='account.UserRace', to='account.Race'),
        ),
    ]
