# Generated by Django 2.0.3 on 2018-04-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceEthnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_ethnicity', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Race/Ethnicity',
                'verbose_name_plural': 'Race/Ethnicities',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='race_ethnicity',
            field=models.ManyToManyField(blank=True, to='account.RaceEthnicity'),
        ),
    ]
